### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#1072]
Size and centering need to do

**Comment by RobiNN1** [comment]
In Nebula theme?

**Comment by meangczac** [comment]
No, in the showsublinks() and admin sitelinks settings. So people can control it without coding.

So far I'm thinking.

Max size, max width, max height (3 controls), and alignment as well.

But for alignment, we got issue - we need to create default.css for alignment using media queries. 

.logo-xs-left, .logo-xs-right, and .logo-xs-center
.logo-sm-
.logo-md-
.logo-lg-

Then apply to bootstrap port width...

media (x) and (x) {
.logo-xs-left { text-align:left; }  
}

repeat with others.

Quite some to do ^^;

**Comment by RobiNN1** [comment]
Something like this? 
![bez nazvu](https://cloud.githubusercontent.com/assets/11664877/18809602/5cbbec06-8280-11e6-8e31-f0cfe488f1eb.png)

LESS code: 

``` less
//
// Variables
//
@screen-xs:         480px;
@screen-xs-min:     @screen-xs;
@screen-phone:      @screen-xs-min;
@screen-sm:         768px;
@screen-sm-min:     @screen-sm;
@screen-tablet:     @screen-sm-min;
@screen-md:         992px;
@screen-md-min:     @screen-md;
@screen-desktop:    @screen-md-min;
@screen-lg:         1200px;
@screen-lg-min:     @screen-lg;
@screen-lg-desktop: @screen-lg-min;
@screen-xs-max:     (@screen-sm-min - 1);
@screen-sm-max:     (@screen-md-min - 1);
@screen-md-max:     (@screen-lg-min - 1);
@grid-columns:      12;

//
// Mixins
//
.make-grid-columns(@value) {
  .col(@index) {
    @item: ~".logo-xs-@{index}-@{value}, .logo-sm-@{index}-@{value}, .logo-md-@{index}-@{value}, .logo-lg-@{index}-@{value}";
    .col((@index + 1), @item);
  }
  .col(@index, @list) when (@index =< @grid-columns) {
    @item: ~".logo-xs-@{index}-@{value}, .logo-sm-@{index}-@{value}, .logo-md-@{index}-@{value}, .logo-lg-@{index}-@{value}";
    .col((@index + 1), ~"@{list}, @{item}");
  }
  .col(@index, @list) when (@index > @grid-columns) {
    @{list} {
        text-align: @value;
    }
  }
  .col(1);
}

.float-grid-columns(@class, @type) {
  .col(@index) {
    @item: ~".logo-@{class}-@{index}-@{type}";
    .col((@index + 1), @item);
  }
  .col(@index, @list) when (@index =< @grid-columns) {
    @item: ~".logo-@{class}-@{index}-@{type}";
    .col((@index + 1), ~"@{list}, @{item}");
  }
  .col(@index, @list) when (@index > @grid-columns) {
    @{list} {
      float: @type;
    }
  }
  .col(1);
}

.calc-grid-column(@index, @class, @type) when (@index > 0) {
  .logo-@{class}-@{index}-@{type} {
    @{type}: percentage((@index / @grid-columns));
  }
}

.loop-grid-columns(@index, @class, @type) when (@index >= 0) {
  .calc-grid-column(@index, @class, @type);
  .loop-grid-columns((@index - 1), @class, @type);
}

.make-grid(@class, @type) {
  .float-grid-columns(@class, @type);
  .loop-grid-columns(@grid-columns, @class, @type);
}

// Generate columns
.make-grid-columns(left);
.make-grid-columns(right);
.make-grid-columns(center);

.make-grid(xs, left);
@media (min-width: @screen-sm-min) {
  .make-grid(sm, left);
}
@media (min-width: @screen-md-min) {
  .make-grid(md, left);
}
@media (min-width: @screen-lg-min) {
  .make-grid(lg, left);
}

.make-grid(xs, right);
@media (min-width: @screen-sm-min) {
  .make-grid(sm, right);
}
@media (min-width: @screen-md-min) {
  .make-grid(md, right);
}
@media (min-width: @screen-lg-min) {
  .make-grid(lg, right);
}
```
