### ISSUE TITLE
Text direction

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1924]
Add support for text direction change.

To html tag add dir="'.$locale['text-direction'].'"  (ltr|rtl) and then in themes change styles via
```css
html[dir="rtl"] body {
    direction: rtl;
}
html[dir="rtl"] other-tag {
    /* your styles */
}
```

https://github.com/RobiNN1/PHP-Fusion-Themes/issues/1
